name: group4_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  get: ^4.6.1
  shared_preferences: ^2.0.13
  flutter_slidable: ^3.0.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
